name: video-style

channels:
  - menpo
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=9.0
  - cudnn=7.6.5
  - python=3.6
  - pyqt=5.9.2
  - pillow=8.3.1
  - keras=2.2.4
  - pip
  - pip:
      - opencv-contrib-python==4.4.0.44
      - tensorflow-gpu==1.12.0

